### PR TITLE
Remove old files and Add mailing list page.

### PR DESCRIPTION
**Pull request by Michaelmvv**

### CODE REVIEW

**Comment by tjhorner** [comment]
Why do you make pull requests for every commit?

**Comment by tjhorner** [comment]
Just push directly to master

**Comment by Michaelmvv** [comment]
Because im used to working in bigger groups where pushing to master makes people mad b/c it leads to merge conflicts… And they do not like doing the work of fixing and stuffs…..

**Comment by tjhorner** [comment]
If you're going to merge anyway, then you should push directly to master. If there's a merge conflict, your git client will tell you.

**Pull request merged**
